### ISSUE TITLE
Unable to use xbox game bar

### ISSUE THREAD

**Issue by TechPro424** [MrLoLf/Deborder#2]
Even when in fullscreen and with this mod installed, I can't use xbox game bar
It tells me to choose fullscreen borderless in the game settings

**Comment by MrLoLf** [comment]
That's because this mod is actually just removes the borders of the windowed minecraft client. Maybe [Borderless Mining](https://www.curseforge.com/minecraft/mc-mods/borderless-mining) will work for this.
