### ISSUE TITLE
not entirely fullscreen

### ISSUE THREAD

**Issue by thom-wye** [MrLoLf/Deborder#3]
the borders and top bar are removed properly, but the game is not stretched to the original selected resolution; with 1920x1080, there is a 19 pixel tall bar missing at the bottom; notepad is open in the background of the screenshot.

I tried manually increasing the height of the resolution in the launcher (to 1920x1099), but this actually only makes the missing area taller, and the menu buttons active areas seem to become misaligned with their graphics

![borderless-issue](https://user-images.githubusercontent.com/73465839/175769850-9a389154-5873-404d-8741-03f2b085f686.png)

**Comment by MrLoLf** [comment]
I have found this my self, but I don't know how to fix this because this seems to me like a bug in windows. Maybe you could try [Borderless Mining](https://www.curseforge.com/minecraft/mc-mods/borderless-miningl).

**Comment by LintyCarcass22** [comment]
I had the same issue on windows and found this alternative that works (with varying success) on a wide variety of games. I tried it on minecraft and so far it works flawlessly.

https://github.com/Codeusa/Borderless-Gaming
