### ISSUE TITLE
[Issue] Picture-in-Picture doesn't stay on top

### ISSUE THREAD

**Issue by Zorklis** [MrLoLf/Deborder#4]
Picture-in-Picture is a Chrome browser extension that allows you to watch videos in a floating window (always on top of other windows) so you can keep an eye on what you’re watching while interacting with other sites, or applications.

Issue: currently Minecraft covers it if it's in fullscreen and this mod doesn't fix it, I found that Bordless gaming software solves it but that requires to be ran every single time.

**Comment by MrLoLf** [comment]
This mod is just supposed to remove the Border of the normal windowed client and not to be a borderless full screen window, you could try [Borderless Mining](https://www.curseforge.com/minecraft/mc-mods/borderless-mining) for this application type.
