### ISSUE TITLE
cant maximize window

### ISSUE THREAD

**Issue by shinenyugen** [MrLoLf/Deborder#5]
once i add the mod the minecraft window its small so how do i maximize it?
![Capture](https://user-images.githubusercontent.com/87522263/213913472-d1f56841-6d48-4bb3-9c96-197d19b1e5cb.PNG)

**Comment by MrLoLf** [comment]
In the minecraft launcher of your choice, you can set the start size of your window, set it to what your monitor size is.

**Comment by MrLoLf** [comment]
![Screenshot 2023-02-01 225657](https://user-images.githubusercontent.com/66185550/216172583-ceec148e-03e7-4234-950d-d4a031d4aac5.png)
This is what has to be changed.
